### ISSUE TITLE
Restructure the CompadreData class?

### ISSUE THREAD

**Issue by levisc8** [jonesor/Rcompadre#27] opened 2018-08-21 17:53 UTC
This has kind of been bugging me recently when working on some internal code. Basically, I think the current data structure is a bit more complicated than it needs to be from a programming and usability perspective. The points below outline some potentially beneficial alterations which would require re-writing the `CompadreData` class (but not the `CompadreM` class! :) ), but here's why I think it is a good idea.

- We can still use S4 to ensure rigidity to a point, but use S3 at lower levels that provide users a more straightforward interface. For example, implementing an S4 `CompadreData` class with 2 slots (call them something like `data` and `version`) would likely work. The `data` slot could be a `data.frame` containing a list column of S4 `CompadreM` objects and their associated metadata. This is not an original idea of mine (@patrickbarks in #25 ), but it could simplify a number of features we've discussed (e.g. @patrickbarks suggestions in #26, reordering data for phylogenetic analysis (e.g. @iainmstott 's usage in #22), adding columns, etc) and make methods easier to write (for example, the `[` method would basically just extract the `data` slot, use `[.data.frame`, and return the subsetted object (e.g. #24)). We'd also still retain the beneficial rigidity of the `CompadreM` class in that list-column so that we don't let people accidentally include negative matrix elements, etc. I think this implementation would also reflect the ideas that @iainmstott and @tdjames1 are discussing towards the end the thread in #22. 

- We aren't really retaining the structure of the SQL database with the current `CompadreData` structure anyway. The SQL database schema breaks the metadata up into a variety of other, smaller tables while we lump it all together into the `metadata` slot (which I think is a good thing). Additionally, the SQL database itself is designed to use the publication as the "atomic unit" of organization while our current `CompadreData` structure uses the matrix itself (also a good thing - that's way more intuitive). The SQL database has a very rigid structure once it's implemented, but we can do whatever we want with that structure once it's pulled into R (and we already are taking that approach with the `metadata` table). I don't think we should constrain ourselves to a rigid approach if a more flexible (and simpler) one is available. In short, SQL is rigid, but R doesn't have to be. We should take advantage of that!

- The current `validCompadreData` method only checks to make sure each row of metadata has a matrix associated with it in the `mat` slot. We could change that to check for NAs in the list-column. Otherwise, I'm not sure we actually need to change very much beyond tweaking a few functions.

- Finally, most other database API packages are built on top of S3 (e.g. [BIEN](https://cran.r-project.org/web/packages/BIEN/index.html), [rnoaa](https://cran.r-project.org/web/packages/rnoaa/index.html)) and Compadre doesn't exist in a vacuum; there are real use cases for cross-database analysis (e.g. @robcito 's talk at ESA). I'm not suggesting we abandon S4 entirely (our data is a bit more constrained than others), but it would help with cross-database compatibility to make our interface as similar as possible.

I've started to experiment with this on my fork (hopefully will push tonight/tomorrow). I've been using dplyr syntax for a lot if it, but that's by no means a requirement (I worry less about depending on tidyverse packages - they're generally pretty stable with the introduction of quasi-quotation in  `rlang 0.2.0`, but I understand the concern in general).  Using functions like `map_*` from `purrr` work really well in this set-up and don't constrain the user on what data can be added/subtracted from their analysis. 

Sorry for the wall of text! **tl;dr** -  I think it'll save us a bunch of pain further down the line to change the internal `CompadreData` structure now. Curious to here other thoughts on this approach.

**Comment by iainmstott** [comment] 2018-08-21 18:14
The point that most of the rigid structure is in CompadreM is a very valid one! In terms of changing the structure, I think that if we agree the flexibility afforded by extra dependencies is worth it, and those dependencies won't cause headaches down the line, then I'm down. The proposed structure doesn't intuitively feel very different to the existing one, we're just moving a list to a different place (which would admittedly also allay fears about potential disassociation of the matrices and metadata). Accessor functions can remain the same in terms of usability but with slightly different internal mechanics.

If we want to do it then you're right, we should do it now!

**Comment by tdjames1** [comment] 2018-08-22 09:29
I like the combined `data` slot idea, if it can be done subject to the concerns in the thread mentioned above by @patrickbarks. Thanks for working on this, @levisc8!

**Comment by levisc8** [comment] 2018-08-22 11:04
Hi all,
I've pushed a prototype up [here](https://github.com/levisc8/Rcompadre/tree/devel).  It implements the list-column and provides the standard accessing functions for each `CompadreM` element. I didn't write them for the rest of the database because, well, you can just do `Compadre@data$ColumnYouWant`. I suppose we can add those if there's a desire for them. 

The bottom of the readme contains examples of how this works when you install the package in its current form. Let me know what you think!

In response to @patrickbarks, 

1. I'm not really sure we need true methods for the `CompadreM` class itself (at least in `Rcompadre`. This will probably be less true in `Rage`). In my mind, its primary use in this package is to make sure users don't accidentally violate fundamental rules for matrix models (and that is covered by the `checkValidCompadreM` function that is built in to the definition). Once we get passed those checks, it's basically just a matrix and we can write functions like [these](https://github.com/levisc8/Rcompadre/blob/devel/R/accessors.R) that pull out the elements and subsequently perform computations on them. 
For `Rage` methods that are defined for `CompadreM` class, I think it would work to just write a method that works on a single `CompadreM` object and then either `map`/`lapply` it to the list column or write a `CompadreData` method that applies it for you at the database level (or both if we're feeling wild! ;) ). Does that make sense?
I haven't had any trouble with tne `Rcompadre` side of things so far. On the other hand, I'm also far less experienced in using these models for actual science than the rest of you so it's quite likely that I'm missing something important from the theory/math side (or have just totally misunderstood which methods you were referring to to begin with). 
We _do_ need to write methods for the `CompadreData` class (e.g. `[`). That is fairly straightforward though because we're just operating on a data frame (and version info), albeit one that happens to contain a list of other S4 classes. 

2. Sure, we'd just need to import the `tibble` package and then use that class in the definition instead. Not sure how others feel about that though. Alternatively, the user can just extract the `data.frame` and convert it to whatever they see fit.

3. I don't have much use for the version myself either, but I think it's important to retain it for user reporting in publications. Also, it doesn't really hurt to have it so I figured it should stay for now. I suppose anyone could just pull out the `data` slot and then do with it as they please without us ever knowing though. Not much to be done about that.

I'm interested to see what happens with the API development from Tony and Austin though, I think we could do some much cooler stuff with it than just say "date created", "number of species", etc (there's talk of generating unique links to sets of matrices in each user query, so including that in the version info would be way more helpful I think).

**Comment by patrickbarks** [comment] 2018-08-22 12:12
Awesome!

1. I do think there's an outstanding issue with having the list-column of S4 objects in the data.frame, and it seems related to that thread I referenced. There are lots of things that I could normally do with a data.frame that I can't currently do with Compadre@data, e.g.

```
# these don't work
Compadre@data[1:3,]
head(Compadre@data)
subset(Compadre@data, MatrixDimension == 3)
dplyr::mutate(Compadre@data, MatDimSq = MatrixDimension^2]

# they all throw this error
> Error in prettyNum(.Internal(format(x, trim, digits, nsmall, width, 3L,  : 
  first argument must be atomic

# works in ggplot though!
ggplot(Compadre@data, aes(Lon, Lat)) +
  geom_point()
```

2. Great. Changing `Compadre@data` to a tibble resolves all of the issues I described in point 1, though I don't think that's a solution we actually want to build in.

3. On further thought, I think we should just get rid of the version slot. I don't think it improves reproducibility under the current model, and I expect there will be a better way of achieving reproducibility with a future API (e.g. DOIs or hashes directly mapped to rows, which would fit better in the data slot). But I'll expand on this later/elsewhere.

**Comment by levisc8** [comment] 2018-08-22 12:44
1. Ah yes, I see your point. Interestingly, if you assign all of those failed operations to a value (e.g. `x <- head(Compadre) %>% .[ ,1:47] %>% .`), you get exactly what you'd expect (a lot of data.frame printing).  All of those examples result in something getting printed (unless there's assignment), so I'm pretty sure it's just a bug in the implementation of `show` with respect to the list-column structure rather than an inability to manipulate the `data.frame` itself. I'll see if I can pull apart the method a bit more and figure out what's going on.

2. I'm not really opposed to changing it to a tibble. `purrr` already imports from `tibble` so I'm not sure we incur additional overhead. 

3. I'll leave the "what to do with it in the interim" up to the rest of you ;)

**Comment by patrickbarks** [comment] 2018-08-23 08:40
Ah ya, I see that it's just a printing issue.

```
Compadre@data[1:2,]
traceback()
```

Looks like the problem is that `print.data.frame` calls `format.data.frame`, which formats column by column element by element. When it gets to the `matdata` column it tries to format the first element with `format.default` and fails. The way `format.data.frame` is written, it doesn't seem like adding a `format.CompadreM` method could solve the problem (though my understanding here is limited).

I found [some discussion](https://github.com/r-spatial/sf/issues/117#issuecomment-277514839) of this same issue with printing in the r-spatial `sf` package.

**Comment by tdjames1** [comment] 2018-08-23 09:11
This is also discussed in comments on the SO post that you referenced in [your comment above](https://github.com/jonesor/Rcompadre/issues/27#issuecomment-414939204) :)

**Comment by levisc8** [comment] 2018-08-23 11:33
I suppose this is what I get for trying program with jetlag ;) Sorry about that! 

Is anyone opposed to adding something like `CompadreDF` S3 class to the `data` slot and writing a `print.CompadreDF` method?  If it inherits from `data.frame` as well, I'm not sure we'd lose any functionality, but you'd still be able to print it. 

I pushed a variant to my branch that implements this solution. So far, I haven't run into any of the problems that are presented by using `base` functionality. `head` currently works as well, but it's the same as the `print` method. 

One unfortunate aspect of this solution is that `dplyr` verbs will not work unless the you restore the class after running the verb (e.g. `x <- dplyr::mutate((Compadre@data, MatDimSq = MatrixDimension^2); class(x@data) <- 'CompadreDF'`. Unfortunately, `dplyr` verbs don't preserve the class of the objects they operate on unless you write a method for them that explicitly restores it. Those aren't too difficult to write, but it'd also mean that we have to have the package depend on `dplyr` to access those generics. I'm not really opposed it, but it does mean a bit more work. 

Also, I don't really like the print method I came up with too much, just wanted to make sure one could implement this as a solution. Happy to make alterations to the information it displays.

**Comment by levisc8** [comment] 2018-08-23 20:26
Fair points. However, if we keep the `CompadreData` class to house the `data` and `version` slots, then we'd still need to write methods for them. Alternatively, we could ditch the `version` slot until we have a better alternative and 

1.  turn Compadre into a `tbl` with an S4 list-column and call it a day. 

or 

2. keep it as a `data.frame` with an S4 list-column, make an S3 class for to go with `data.frame`, and just write our own `print` method (doesn't take long).

Assuming DOIs or hashes are implemented in the database, those would just become another column in the data.

**Comment by patrickbarks** [comment] 2018-08-24 06:42
I favour option 1. Here's my pitch for ditching the `version` slot:

1. It doesn't improve reproducibility
2. The benefits of `db` being a single flat structure are huge


(1.) I'm assuming the purpose of version is primarily reproducibility (e.g. version number and date created)? It also includes a link to the user agreement and some db summary statistics.

Reproducibility currently comes from knowing the db version number, which is already available in the `.RData` file name and from the download page (where the release date and user agreement are also available). Anyone should be able to get the same db if they know the version number.

After that, reproducibility requires the R code used to conduct any given analysis. Knowing the time/date of the last db subset or merger isn't particularly informative. If a user really wants a time-stamp they could use `save(db, 'my_db.RData')`.

With the future API, I'm guessing reproducibility will either come from row-specific DOIs or a db-wide version number. If the former, DOI's can be incorporated into the flat data structure. If the latter, perhaps the version number could be printed by a future `Rcompadre::fetch_db` function, e.g.

```
# download most recent version
db <- Rcompadre::fetch_db()
> # This is COMPADRE version 2.5.681 (release date 05/11/2017)
> # See user agreement at http://www.compadre-db.org/Page/UserAgreement

# re-download version 2.5.681
db <- Rcompadre::fetch_db(vers = '2.5.681')
```

If we still really want the proposed flat `db` to retain version info, we could alternatively set it as an attribute (either of a data.frame or tibble).

`attr(compadre, 'version') <- list(version = '2.5.681', date_created = '05/11/2017')`


(2.) Having `db` be a single flat structure (either data.frame or tibble) gives the user complete flexibility to use regular data.frame operations or tidyverse functions, with which they are already more familiar.

`subsetDB` is just `base::subset` or `dplyr::filter`, and `mergeDB` is just `base::rbind`.

The flat structure is also maximally useful for piping, because we no longer have to worry about nested levels. E.g. We can pipe the whole db into one of our own functions (e.g. `cleanDB`), and then directly into any data.frame or tidyverse function, and then directly into ggplot! We don't have to break up the pipe sequence to switch from the db-level to some lower level (e.g. db@data).

**Comment by patrickbarks** [comment] 2018-08-26 17:15
I built on @levisc8's ideas above to test out a [fully-tidy version of Rcompadre](https://github.com/patrickbarks/Rcompadre/tree/devel) (i.e. completely flat `db` structure). It includes some big changes apart from just the tidy main structure (incl. #28 and #29), but these latter changes are just my personal preferences. The magic is in `db` being a single flat structure, in my opinion.

**Comment by levisc8** [comment] 2018-08-27 14:35
Version as an attribute and removing the `CompadreData` class both work for me. 

On the other hand, I'm not sure I agree w/ getting rid of the `CompadreM` class. See my comment in #29 for more on that.

**Comment by jonesor** [comment] 2018-08-27 14:38
I'm just trying to catch up with all of this! Great work everyone!
I fully agree that the minor cost of ditching the version slot is worth it for the benefits in useability that will bring. The current overly complicated structure of the compadre R object is always a pain for new users (and old users too!). 
It made sense at the time, but I'd welcome a flat structure. For old code compatibility reasons it would be good to have a function to translate between those structures.

**Comment by levisc8** [comment] 2018-08-28 18:11
Just to clarify, do you mean translate between the current list structure or translate from the S4 class to the flattened db?

**Comment by jonesor** [comment] 2018-08-30 10:14
@levisc8 I meant to translate from current list structure. i.e. so we can apply newly-developed methods to the old databases.

**Comment by iainmstott** [comment] 2018-09-10 14:01
I can't say that I've read through all of these comments... or looked at the code.

I don't mind a flat structure in the data slot, but I think the matrices still need to stay as the CompadreM S4 objects, otherwise what's the point of this whole exercise? I like the idea that the matrices would be tied more closely to the metadata, however.

I do not like the idea of tying this too closely to dplyr / purr / tibble, at least to the point that people need to use dplyr / purr / tibble to use the data. Not everybody uses data this way. I'm still keen to avoid dependencies if possible, even if they're pretty stable ones. 

Can we not have a basic function that converts the database into a friendly flat form, but retain the integrity of the original database objects (even if these are mutated from what was originally chosen)? Then people can do whatever they like to the flat databases, but our original goal of providing something with a relatively defined structure still stands. Such a function would basically be analagous to the DB2flat function that already exists for converting into a simple data.frame (useful for providing alongside publication as e.g. a csv).

We need to include the version. We're really not being good, transparent, accountable researchers if we don't, and it's going to become even more important once it gets to the API

**Comment by levisc8** [comment] 2018-11-15 08:21
Hi all,
sorry, I sort of fell off the face of the planet for a couple months (field work...). I think @iainmstott's work in #32 and @jonesor's followup have pretty much solidified a move to a single table w/ a list column. Unless anyone objects, I'd move to close this issue.

**Comment by iainmstott** [comment] 2018-11-15 10:36
Can do, although there is still scope to revisit this (and leave it open) if opinions differ; the functions are almost indifferent now to what the underlying structure is (although methods would of course need to be changed). We forged ahead with these particular changes mainly to have a functioning version of the package for December BES workshop.

**Comment by levisc8** [comment] 2018-11-15 11:07
Fair enough - there isn't really any down side to leaving it open too :)

**Comment by patrickbarks** [comment] 2018-11-27 13:38
I'm on board with the current implementation. I think I was the only hold-out, so closing this issue. Props to @levisc8 and @iainmstott for the vision, and implementation!

**Closed by patrickbarks** 2018-11-27 13:38 UTC
